repos:
  - repo: https://github.com/pycqa/isort
    rev: e44834b7b294701f596c9118d6c370f86671a50d # tag: 5.12.0
    hooks:
    - name: isort
      id: isort
      args: ["."]
  - repo: https://github.com/psf/black
    rev: f6c139c5215ce04fd3e73a900f1372942d58eca0 # tag: 22.6.0
    hooks:
    - name: black
      id: black
