[tool.isort]
profile = "black"

[tool.black]
target_version = ["py38"]
exclude = """
(
  /(
    | .git
    | venv
    | .github
  )/
)
"""

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
command_line = "-m pytest tests"
source = ["ml_check", "tests"]
data_file = "coverage/.report"

[tool.coverage.report]
show_missing = true
skip_covered = true
skip_empty = true

[tool.coverage.html]
directory = "coverage"
