name: ktml-check
summary: Kernel Team mailing list utility
description: |
      Query and report the status of patches on the public Canonical
      Kernel Team mailing list.
adopt-info: ktml-check
license: GPL-2.0
base: core20
compression: lzo 
grade: stable # 'stable' 'devel'
confinement: strict # 'strict' 'devmode'
architectures: [amd64]

apps:
  ktml-check:
    command: bin/ktml-check
    plugs: [home, network, network-bind]

parts:
  ktml-check:
    plugin: python
    source: https://github.com/corytodd/ktml-check.git
    source-type: git
    requirements: 
      - requirements.txt
    parse-info: [setup.py]
