name: ktml-check
summary: Kernel Team mailing list utility
description: |
      Query and report the status of patches on the public Canonical
      Kernel Team mailing list.
adopt-info: ktml-check
base: core20
compression: lzo 
grade: stable # 'stable' 'devel'
confinement: strict # 'strict' 'devmode'
architectures: [amd64]

apps:
  ktml-check:
    command: bin/ktml-check
    plugs: [home, network, network-bind]

parts:
  ktml-check:
    plugin: python
    source: .
    source-type: local
    requirements: 
      - requirements.txt
    override-build: |
      snapcraftctl pull
      VERSION="$(git --work-tree "$SNAPCRAFT_PROJECT_DIR" describe --tags)"
      snapcraftctl build
      snapcraftctl set-version "$VERSION"
